/**
 * Lyricast Dictionary API
 * API для работы со справочниками песен/Библии на основе SQLite
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SongBookExportLyric } from './songBookExportLyric';
import { SongBookExportBookName } from './songBookExportBookName';


/**
 * Песня в экспортируемой книге
 */
export interface SongBookExportSong { 
    number: number;
    title: string;
    key: string;
    keySignature: string;
    author: string;
    meta: Array<string>;
    lyrics: Array<SongBookExportLyric>;
    ref?: string | null;
    category?: string | null;
    bookName: SongBookExportBookName;
}

