export const ElectronActionEvents = {
  GET_APP_VERSION: 'GET_APP_VERSION',
  GET_WINDOW_TYPE: 'GET_WINDOW_TYPE',
  OPEN_WINDOW: 'OPEN_WINDOW',
  CLOSE_WINDOW: 'CLOSE_WINDOW',
  PING: 'PING',
} as const;
