// @ts-nocheck
/**
 * Dictionary API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AuthControllerLogin200Response } from '../model/models';
import { LoginDto } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface AuthControllerLoginRequestParams {
    loginDto: LoginDto;
}


export interface AuthServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Авторизация по email, выдача токена
     * 
     * @endpoint post /api/auth/login
* @param requestParameters
     */
    authControllerLogin(requestParameters: AuthControllerLoginRequestParams, extraHttpRequestParams?: any): Observable<AuthControllerLogin200Response>;

}
