// @ts-nocheck
/**
 * Dictionary API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CatalogDto } from '../model/models';
import { CreateCatalogDto } from '../model/models';
import { UpdateCatalogDto } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface CatalogsControllerCreateRequestParams {
    createCatalogDto: CreateCatalogDto;
}

export interface CatalogsControllerFindOneRequestParams {
    id: number;
}

export interface CatalogsControllerRemoveRequestParams {
    id: number;
}

export interface CatalogsControllerUpdateRequestParams {
    id: number;
    updateCatalogDto: UpdateCatalogDto;
}

export interface CatalogsControllerVersionRequestParams {
    id: number;
}


export interface CatalogsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint post /api/catalogs
* @param requestParameters
     */
    catalogsControllerCreate(requestParameters: CatalogsControllerCreateRequestParams, extraHttpRequestParams?: any): Observable<CatalogDto>;

    /**
     * 
     * 
     * @endpoint get /api/catalogs
*/
    catalogsControllerFindAll(extraHttpRequestParams?: any): Observable<Array<CatalogDto>>;

    /**
     * 
     * 
     * @endpoint get /api/catalogs/{id}
* @param requestParameters
     */
    catalogsControllerFindOne(requestParameters: CatalogsControllerFindOneRequestParams, extraHttpRequestParams?: any): Observable<CatalogDto>;

    /**
     * 
     * 
     * @endpoint delete /api/catalogs/{id}
* @param requestParameters
     */
    catalogsControllerRemove(requestParameters: CatalogsControllerRemoveRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint put /api/catalogs/{id}
* @param requestParameters
     */
    catalogsControllerUpdate(requestParameters: CatalogsControllerUpdateRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint get /api/catalogs/{id}/version
* @param requestParameters
     */
    catalogsControllerVersion(requestParameters: CatalogsControllerVersionRequestParams, extraHttpRequestParams?: any): Observable<{}>;

}
