// @ts-nocheck
/**
 * Lyricast Dictionary API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiPhpActionAuthLoginPostRequest } from '../model/models';
import { ApiPhpActionBookVersionsCheckPost200Response } from '../model/models';
import { ApiPhpActionDbDeletePost200Response } from '../model/models';
import { ApiPhpActionExportBookGet400Response } from '../model/models';
import { ApiPhpActionExportBookGet404Response } from '../model/models';
import { ApiPhpActionPingGet200Response } from '../model/models';
import { ApiPhpActionRegistryListGet200Response } from '../model/models';
import { ApiPhpActionSongGetGet200Response } from '../model/models';
import { ApiPhpActionSongSavePost200Response } from '../model/models';
import { AuthResponse } from '../model/models';
import { BookVersionsCheckRequest } from '../model/models';
import { SongBookExport } from '../model/models';
import { SongSaveRequest } from '../model/models';
import { SongSearchResponse } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface ApiPhpGetRequestParams {
    action: string;
    db?: string;
}

export interface ApiPhpactionauthLoginPostRequestParams {
    apiPhpActionAuthLoginPostRequest: ApiPhpActionAuthLoginPostRequest;
}

export interface ApiPhpactionbookVersionsCheckPostRequestParams {
    bookVersionsCheckRequest: BookVersionsCheckRequest;
}

export interface ApiPhpactiondbDeletePostRequestParams {
    db: string;
}

export interface ApiPhpactiondownloadDbGetRequestParams {
    db: string;
}

export interface ApiPhpactionexportBookGetRequestParams {
    db?: string;
    fileKey?: string;
}

export interface ApiPhpactionsongDeletePostRequestParams {
    db?: string;
    id?: number;
    id2?: number;
}

export interface ApiPhpactionsongGetGetRequestParams {
    id: number;
    db?: string;
}

export interface ApiPhpactionsongSavePostRequestParams {
    songSaveRequest: SongSaveRequest;
    db?: string;
}

export interface ApiPhpactionsongSearchGetRequestParams {
    db?: string;
    query?: string;
    number?: number;
    page?: number;
    pageSize?: number;
    includeLyrics?: 0 | 1;
}


export interface DefaultServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * API router
     * Все действия задаются через query-параметр &#x60;action&#x60;. 
     * @endpoint get /api.php
* @param requestParameters
     */
    apiPhpGet(requestParameters: ApiPhpGetRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Авторизация по email, выдача токена
     * Создаёт/обновляет пользователя и устройство, возвращает токен сессии. Поддерживает JSON (&#x60;application/json&#x60;) и form-urlencoded (&#x60;application/x-www-form-urlencoded&#x60;). 
     * @endpoint post /api.php?action=auth.login
* @param requestParameters
     */
    apiPhpactionauthLoginPost(requestParameters: ApiPhpactionauthLoginPostRequestParams, extraHttpRequestParams?: any): Observable<AuthResponse>;

    /**
     * Проверить, какие справочники (книги) свежее на сервере
     * Если в теле запроса не передан массив books или он пустой, возвращает все доступные справочники с их версиями. Иначе клиент присылает массив книг (song_books.file_key) и их локальных версий, а сервер возвращает список книг, у которых версия на сервере больше. Для каждой такой книги возвращается ссылка для скачивания (экспорт в JSON). Книги ищутся во всех доступных SQLite файлах по fileKey. 
     * @endpoint post /api.php?action=book.versions.check
* @param requestParameters
     */
    apiPhpactionbookVersionsCheckPost(requestParameters: ApiPhpactionbookVersionsCheckPostRequestParams, extraHttpRequestParams?: any): Observable<ApiPhpActionBookVersionsCheckPost200Response>;

    /**
     * Удалить SQLite-файл и связанные служебные файлы
     * 
     * @endpoint post /api.php?action=db.delete
* @param requestParameters
     */
    apiPhpactiondbDeletePost(requestParameters: ApiPhpactiondbDeletePostRequestParams, extraHttpRequestParams?: any): Observable<ApiPhpActionDbDeletePost200Response>;

    /**
     * Скачать SQLite-файл (требует авторизации)
     * 
     * @endpoint get /api.php?action=download.db
* @param requestParameters
     */
    apiPhpactiondownloadDbGet(requestParameters: ApiPhpactiondownloadDbGetRequestParams, extraHttpRequestParams?: any): Observable<Blob>;

    /**
     * Экспорт книги песен в JSON (требует авторизации)
     * Возвращает структуру ISongBook на основе SQLite-базы, включая метаданные книги. Требует авторизацию. Если параметр &#x60;fileKey&#x60; не указан, а в БД только одна книга, она будет выбрана автоматически. Иначе &#x60;fileKey&#x60; обязателен. 
     * @endpoint get /api.php?action=exportBook
* @param requestParameters
     */
    apiPhpactionexportBookGet(requestParameters: ApiPhpactionexportBookGetRequestParams, extraHttpRequestParams?: any): Observable<SongBookExport>;

    /**
     * Проверка доступности API
     * 
     * @endpoint get /api.php?action=ping
*/
    apiPhpactionpingGet(extraHttpRequestParams?: any): Observable<ApiPhpActionPingGet200Response>;

    /**
     * Список SQLite-справочников
     * 
     * @endpoint get /api.php?action=registry.list
*/
    apiPhpactionregistryListGet(extraHttpRequestParams?: any): Observable<ApiPhpActionRegistryListGet200Response>;

    /**
     * Удалить песню
     * 
     * @endpoint post /api.php?action=song.delete
* @param requestParameters
     */
    apiPhpactionsongDeletePost(requestParameters: ApiPhpactionsongDeletePostRequestParams, extraHttpRequestParams?: any): Observable<ApiPhpActionSongSavePost200Response>;

    /**
     * Получить одну песню (полную)
     * 
     * @endpoint get /api.php?action=song.get
* @param requestParameters
     */
    apiPhpactionsongGetGet(requestParameters: ApiPhpactionsongGetGetRequestParams, extraHttpRequestParams?: any): Observable<ApiPhpActionSongGetGet200Response>;

    /**
     * Создание или обновление песни
     * 
     * @endpoint post /api.php?action=song.save
* @param requestParameters
     */
    apiPhpactionsongSavePost(requestParameters: ApiPhpactionsongSavePostRequestParams, extraHttpRequestParams?: any): Observable<ApiPhpActionSongSavePost200Response>;

    /**
     * Поиск песен
     * 
     * @endpoint get /api.php?action=song.search
* @param requestParameters
     */
    apiPhpactionsongSearchGet(requestParameters: ApiPhpactionsongSearchGetRequestParams, extraHttpRequestParams?: any): Observable<SongSearchResponse>;

}
