// @ts-nocheck
/**
 * Dictionary API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AppControllerPing200Response } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface HealthServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Проверка доступности API
     * 
     * @endpoint get /api/ping
*/
    appControllerPing(extraHttpRequestParams?: any): Observable<AppControllerPing200Response>;

}
