// @ts-nocheck
/**
 * Dictionary API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateSongBookDto } from '../model/models';
import { CreateSongDto } from '../model/models';
import { ImportSongBookDto } from '../model/models';
import { RegistryResponseDto } from '../model/models';
import { SongBookExportDto } from '../model/models';
import { UpdateSongDto } from '../model/models';
import { VersionsCheckRequestDto } from '../model/models';
import { VersionsCheckResponseDto } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface SongsControllerCheckVersionsRequestParams {
    versionsCheckRequestDto: VersionsCheckRequestDto;
}

export interface SongsControllerCreateRequestParams {
    createSongDto: CreateSongDto;
}

export interface SongsControllerCreateSongBookRequestParams {
    createSongBookDto: CreateSongBookDto;
}

export interface SongsControllerExportSongBookRequestParams {
    songBookId: number;
}

export interface SongsControllerFindAllRequestParams {
    songBookId: number;
    q?: string;
    page?: number;
    pageSize?: number;
}

export interface SongsControllerFindOneRequestParams {
    id: number;
}

export interface SongsControllerImportSongBookRequestParams {
    importSongBookDto: ImportSongBookDto;
}

export interface SongsControllerRemoveRequestParams {
    id: number;
}

export interface SongsControllerUpdateRequestParams {
    id: number;
    updateSongDto: UpdateSongDto;
}

export interface SongsControllerUpdateSongBookMetaRequestParams {
    songBookId: number;
    body: object;
}


export interface SongsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Проверить, какие книги новее на сервере
     * 
     * @endpoint post /api/songs/versions/check
* @param requestParameters
     */
    songsControllerCheckVersions(requestParameters: SongsControllerCheckVersionsRequestParams, extraHttpRequestParams?: any): Observable<VersionsCheckResponseDto>;

    /**
     * Создание песни
     * 
     * @endpoint post /api/songs
* @param requestParameters
     */
    songsControllerCreate(requestParameters: SongsControllerCreateRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Создать пустой SongBook без импорта JSON
     * 
     * @endpoint post /api/songs/song-books
* @param requestParameters
     */
    songsControllerCreateSongBook(requestParameters: SongsControllerCreateSongBookRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Экспорт книги песен в JSON (SongBookExport)
     * 
     * @endpoint get /api/songs/song-books/{songBookId}/export
* @param requestParameters
     */
    songsControllerExportSongBook(requestParameters: SongsControllerExportSongBookRequestParams, extraHttpRequestParams?: any): Observable<SongBookExportDto>;

    /**
     * Список песен по сборнику
     * 
     * @endpoint get /api/songs
* @param requestParameters
     */
    songsControllerFindAll(requestParameters: SongsControllerFindAllRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Получить песню
     * 
     * @endpoint get /api/songs/{id}
* @param requestParameters
     */
    songsControllerFindOne(requestParameters: SongsControllerFindOneRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Импорт SongBook из JSON в PostgreSQL
     * 
     * @endpoint post /api/songs/song-books/import
* @param requestParameters
     */
    songsControllerImportSongBook(requestParameters: SongsControllerImportSongBookRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Реестр сборников (registry.list)
     * 
     * @endpoint get /api/songs/registry
*/
    songsControllerRegistry(extraHttpRequestParams?: any): Observable<RegistryResponseDto>;

    /**
     * Удалить песню
     * 
     * @endpoint delete /api/songs/{id}
* @param requestParameters
     */
    songsControllerRemove(requestParameters: SongsControllerRemoveRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Обновить песню
     * 
     * @endpoint put /api/songs/{id}
* @param requestParameters
     */
    songsControllerUpdate(requestParameters: SongsControllerUpdateRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Обновить мета-информацию сборника (song_book_meta)
     * 
     * @endpoint patch /api/songs/song-books/{songBookId}/meta
* @param requestParameters
     */
    songsControllerUpdateSongBookMeta(requestParameters: SongsControllerUpdateSongBookMetaRequestParams, extraHttpRequestParams?: any): Observable<{}>;

}
