/* 🤖 this file was generated by svg-to-ts */

import type { LyriIcon } from './src/lyri-icons/lyri-svg-icon.model';

export type LyriIconNameSubset<T extends Readonly<LyriIcon[]>> =
  T[number]['name'];

export * from './src/lyri-icons/lyri-bible.icon';
export * from './src/lyri-icons/lyri-control.icon';
export * from './src/lyri-icons/lyri-song-lyrics.icon';
export * from './src/lyri-icons/lyri-storyboard.icon';
export * from './src/lyri-icons/lyri-svg-icon.model';
