// @ts-nocheck
/**
 * Dictionary API
 * API for dictionaries (songs, bibles, programs)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Injectable, Optional } from '@nestjs/common';
import { HttpService } from '@nestjs/axios';
import type { AxiosRequestConfig, AxiosResponse } from 'axios';
import { Observable, from, of, switchMap } from 'rxjs';
import { AuthControllerLogin200Response } from '../model/authControllerLogin200Response';
import { LoginDto } from '../model/loginDto';
import { Configuration } from '../configuration';
import { COLLECTION_FORMATS } from '../variables';
import { AuthServiceInterface } from './auth.serviceInterface';

/**
 * Request parameters for authControllerLogin operation in AuthService.
 * @export
 * @interface AuthServiceAuthControllerLoginRequest
 */
export interface AuthServiceAuthControllerLoginRequest {
    /**
     * 
     * @type {LoginDto}
     * @memberof AuthServiceAuthControllerLogin
     */
    readonly 'LoginDto': LoginDto
}


@Injectable()
export class AuthService implements AuthServiceInterface {

    protected basePath = 'http://localhost';
    public defaultHeaders: Record<string,string> = {};
    public configuration = new Configuration();
    protected httpClient: HttpService;

    constructor(httpClient: HttpService, @Optional() configuration: Configuration) {
        this.configuration = configuration || this.configuration;
        this.basePath = configuration?.basePath || this.basePath;
        this.httpClient = configuration?.httpClient || httpClient;
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        return consumes.includes(form);
    }

    /**
     * Авторизация по email, выдача токена
     * 
     * @param {AuthServiceAuthControllerLoginRequest} requestParameters Request parameters.
     * @param {*} [authControllerLoginOpts.config] Override http request option.
     */
    public authControllerLogin(requestParameters: AuthServiceAuthControllerLoginRequest, authControllerLoginOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<AuthControllerLogin200Response>>;
    public authControllerLogin(requestParameters: AuthServiceAuthControllerLoginRequest, authControllerLoginOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        const {
            'LoginDto': loginDto,
        } = requestParameters;

        if (loginDto === null || loginDto === undefined) {
            throw new Error('Required parameter loginDto was null or undefined when calling authControllerLogin.');
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.post<AuthControllerLogin200Response>(`${this.basePath}/api/auth/login`,
                    loginDto,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...authControllerLoginOpts?.config,
                        headers: {...headers, ...authControllerLoginOpts?.config?.headers},
                    }
                );
            })
        );
    }
}
