// @ts-nocheck
/**
 * Dictionary API
 * API for dictionaries (songs, bibles, programs)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Observable }                                        from 'rxjs';

import { AuthControllerLogin200Response } from '../model/authControllerLogin200Response';
import { LoginDto } from '../model/loginDto';


import { Configuration }                                     from '../configuration';


export interface AuthServiceInterface {
    defaultHeaders: {};
    configuration: Configuration;

    /**
    * Авторизация по email, выдача токена
    * 
    * @param loginDto 
    */
    authControllerLogin(loginDto: LoginDto, extraHttpRequestParams?: any): Observable<AuthControllerLogin200Response>;

}
