// @ts-nocheck
/**
 * Dictionary API
 * API for dictionaries (songs, bibles, programs)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Observable }                                        from 'rxjs';

import { CatalogDto } from '../model/catalogDto';
import { CreateCatalogDto } from '../model/createCatalogDto';
import { UpdateCatalogDto } from '../model/updateCatalogDto';


import { Configuration }                                     from '../configuration';


export interface CatalogsServiceInterface {
    defaultHeaders: {};
    configuration: Configuration;

    /**
    * 
    * 
    * @param createCatalogDto 
    */
    catalogsControllerCreate(createCatalogDto: CreateCatalogDto, extraHttpRequestParams?: any): Observable<CatalogDto>;

    /**
    * 
    * 
    */
    catalogsControllerFindAll(extraHttpRequestParams?: any): Observable<Array<CatalogDto>>;

    /**
    * 
    * 
    * @param id 
    */
    catalogsControllerFindOne(id: number, extraHttpRequestParams?: any): Observable<CatalogDto>;

    /**
    * 
    * 
    * @param id 
    */
    catalogsControllerRemove(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
    * 
    * 
    * @param id 
    * @param updateCatalogDto 
    */
    catalogsControllerUpdate(id: number, updateCatalogDto: UpdateCatalogDto, extraHttpRequestParams?: any): Observable<{}>;

    /**
    * 
    * 
    * @param id 
    */
    catalogsControllerVersion(id: number, extraHttpRequestParams?: any): Observable<{}>;

}
