// @ts-nocheck
/**
 * Dictionary API
 * API for dictionaries (songs, bibles, programs)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Injectable, Optional } from '@nestjs/common';
import { HttpService } from '@nestjs/axios';
import type { AxiosRequestConfig, AxiosResponse } from 'axios';
import { Observable, from, of, switchMap } from 'rxjs';
import { CatalogDto } from '../model/catalogDto';
import { CreateCatalogDto } from '../model/createCatalogDto';
import { UpdateCatalogDto } from '../model/updateCatalogDto';
import { Configuration } from '../configuration';
import { COLLECTION_FORMATS } from '../variables';
import { CatalogsServiceInterface } from './catalogs.serviceInterface';

/**
 * Request parameters for catalogsControllerCreate operation in CatalogsService.
 * @export
 * @interface CatalogsServiceCatalogsControllerCreateRequest
 */
export interface CatalogsServiceCatalogsControllerCreateRequest {
    /**
     * 
     * @type {CreateCatalogDto}
     * @memberof CatalogsServiceCatalogsControllerCreate
     */
    readonly 'CreateCatalogDto': CreateCatalogDto
}

/**
 * Request parameters for catalogsControllerFindOne operation in CatalogsService.
 * @export
 * @interface CatalogsServiceCatalogsControllerFindOneRequest
 */
export interface CatalogsServiceCatalogsControllerFindOneRequest {
    /**
     * 
     * @type {number}
     * @memberof CatalogsServiceCatalogsControllerFindOne
     */
    readonly id: number
}

/**
 * Request parameters for catalogsControllerRemove operation in CatalogsService.
 * @export
 * @interface CatalogsServiceCatalogsControllerRemoveRequest
 */
export interface CatalogsServiceCatalogsControllerRemoveRequest {
    /**
     * 
     * @type {number}
     * @memberof CatalogsServiceCatalogsControllerRemove
     */
    readonly id: number
}

/**
 * Request parameters for catalogsControllerUpdate operation in CatalogsService.
 * @export
 * @interface CatalogsServiceCatalogsControllerUpdateRequest
 */
export interface CatalogsServiceCatalogsControllerUpdateRequest {
    /**
     * 
     * @type {number}
     * @memberof CatalogsServiceCatalogsControllerUpdate
     */
    readonly id: number

    /**
     * 
     * @type {UpdateCatalogDto}
     * @memberof CatalogsServiceCatalogsControllerUpdate
     */
    readonly 'UpdateCatalogDto': UpdateCatalogDto
}

/**
 * Request parameters for catalogsControllerVersion operation in CatalogsService.
 * @export
 * @interface CatalogsServiceCatalogsControllerVersionRequest
 */
export interface CatalogsServiceCatalogsControllerVersionRequest {
    /**
     * 
     * @type {number}
     * @memberof CatalogsServiceCatalogsControllerVersion
     */
    readonly id: number
}


@Injectable()
export class CatalogsService implements CatalogsServiceInterface {

    protected basePath = 'http://localhost';
    public defaultHeaders: Record<string,string> = {};
    public configuration = new Configuration();
    protected httpClient: HttpService;

    constructor(httpClient: HttpService, @Optional() configuration: Configuration) {
        this.configuration = configuration || this.configuration;
        this.basePath = configuration?.basePath || this.basePath;
        this.httpClient = configuration?.httpClient || httpClient;
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        return consumes.includes(form);
    }

    /**
     * 
     * 
     * @param {CatalogsServiceCatalogsControllerCreateRequest} requestParameters Request parameters.
     * @param {*} [catalogsControllerCreateOpts.config] Override http request option.
     */
    public catalogsControllerCreate(requestParameters: CatalogsServiceCatalogsControllerCreateRequest, catalogsControllerCreateOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<CatalogDto>>;
    public catalogsControllerCreate(requestParameters: CatalogsServiceCatalogsControllerCreateRequest, catalogsControllerCreateOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        const {
            'CreateCatalogDto': createCatalogDto,
        } = requestParameters;

        if (createCatalogDto === null || createCatalogDto === undefined) {
            throw new Error('Required parameter createCatalogDto was null or undefined when calling catalogsControllerCreate.');
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearer) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.post<CatalogDto>(`${this.basePath}/api/catalogs`,
                    createCatalogDto,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...catalogsControllerCreateOpts?.config,
                        headers: {...headers, ...catalogsControllerCreateOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * 
     * 
     * @param {*} [catalogsControllerFindAllOpts.config] Override http request option.
     */
    public catalogsControllerFindAll(catalogsControllerFindAllOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<Array<CatalogDto>>>;
    public catalogsControllerFindAll(catalogsControllerFindAllOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearer) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<Array<CatalogDto>>(`${this.basePath}/api/catalogs`,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...catalogsControllerFindAllOpts?.config,
                        headers: {...headers, ...catalogsControllerFindAllOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * 
     * 
     * @param {CatalogsServiceCatalogsControllerFindOneRequest} requestParameters Request parameters.
     * @param {*} [catalogsControllerFindOneOpts.config] Override http request option.
     */
    public catalogsControllerFindOne(requestParameters: CatalogsServiceCatalogsControllerFindOneRequest, catalogsControllerFindOneOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<CatalogDto>>;
    public catalogsControllerFindOne(requestParameters: CatalogsServiceCatalogsControllerFindOneRequest, catalogsControllerFindOneOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        const {
            id,
        } = requestParameters;

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling catalogsControllerFindOne.');
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearer) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<CatalogDto>(`${this.basePath}/api/catalogs/${encodeURIComponent(String(id))}`,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...catalogsControllerFindOneOpts?.config,
                        headers: {...headers, ...catalogsControllerFindOneOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * 
     * 
     * @param {CatalogsServiceCatalogsControllerRemoveRequest} requestParameters Request parameters.
     * @param {*} [catalogsControllerRemoveOpts.config] Override http request option.
     */
    public catalogsControllerRemove(requestParameters: CatalogsServiceCatalogsControllerRemoveRequest, catalogsControllerRemoveOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<any>>;
    public catalogsControllerRemove(requestParameters: CatalogsServiceCatalogsControllerRemoveRequest, catalogsControllerRemoveOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        const {
            id,
        } = requestParameters;

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling catalogsControllerRemove.');
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearer) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.delete<any>(`${this.basePath}/api/catalogs/${encodeURIComponent(String(id))}`,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...catalogsControllerRemoveOpts?.config,
                        headers: {...headers, ...catalogsControllerRemoveOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * 
     * 
     * @param {CatalogsServiceCatalogsControllerUpdateRequest} requestParameters Request parameters.
     * @param {*} [catalogsControllerUpdateOpts.config] Override http request option.
     */
    public catalogsControllerUpdate(requestParameters: CatalogsServiceCatalogsControllerUpdateRequest, catalogsControllerUpdateOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<any>>;
    public catalogsControllerUpdate(requestParameters: CatalogsServiceCatalogsControllerUpdateRequest, catalogsControllerUpdateOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        const {
            id,
            'UpdateCatalogDto': updateCatalogDto,
        } = requestParameters;

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling catalogsControllerUpdate.');
        }

        if (updateCatalogDto === null || updateCatalogDto === undefined) {
            throw new Error('Required parameter updateCatalogDto was null or undefined when calling catalogsControllerUpdate.');
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearer) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.put<any>(`${this.basePath}/api/catalogs/${encodeURIComponent(String(id))}`,
                    updateCatalogDto,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...catalogsControllerUpdateOpts?.config,
                        headers: {...headers, ...catalogsControllerUpdateOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * 
     * 
     * @param {CatalogsServiceCatalogsControllerVersionRequest} requestParameters Request parameters.
     * @param {*} [catalogsControllerVersionOpts.config] Override http request option.
     */
    public catalogsControllerVersion(requestParameters: CatalogsServiceCatalogsControllerVersionRequest, catalogsControllerVersionOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<any>>;
    public catalogsControllerVersion(requestParameters: CatalogsServiceCatalogsControllerVersionRequest, catalogsControllerVersionOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        const {
            id,
        } = requestParameters;

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling catalogsControllerVersion.');
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearer) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<any>(`${this.basePath}/api/catalogs/${encodeURIComponent(String(id))}/version`,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...catalogsControllerVersionOpts?.config,
                        headers: {...headers, ...catalogsControllerVersionOpts?.config?.headers},
                    }
                );
            })
        );
    }
}
