// @ts-nocheck
/**
 * Lyricast Dictionary API
 * API для работы со справочниками песен/Библии на основе SQLite
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Injectable, Optional } from '@nestjs/common';
import { HttpService } from '@nestjs/axios';
import type { AxiosRequestConfig, AxiosResponse } from 'axios';
import { Observable, from, of, switchMap } from 'rxjs';
import { ApiPhpActionAuthLoginPostRequest } from '../model/apiPhpActionAuthLoginPostRequest';
import { ApiPhpActionBookVersionsCheckPost200Response } from '../model/apiPhpActionBookVersionsCheckPost200Response';
import { ApiPhpActionDbDeletePost200Response } from '../model/apiPhpActionDbDeletePost200Response';
import { ApiPhpActionExportBookGet400Response } from '../model/apiPhpActionExportBookGet400Response';
import { ApiPhpActionExportBookGet404Response } from '../model/apiPhpActionExportBookGet404Response';
import { ApiPhpActionPingGet200Response } from '../model/apiPhpActionPingGet200Response';
import { ApiPhpActionRegistryListGet200Response } from '../model/apiPhpActionRegistryListGet200Response';
import { ApiPhpActionSongGetGet200Response } from '../model/apiPhpActionSongGetGet200Response';
import { ApiPhpActionSongSavePost200Response } from '../model/apiPhpActionSongSavePost200Response';
import { AuthResponse } from '../model/authResponse';
import { BookVersionsCheckRequest } from '../model/bookVersionsCheckRequest';
import { SongBookExport } from '../model/songBookExport';
import { SongSaveRequest } from '../model/songSaveRequest';
import { SongSearchResponse } from '../model/songSearchResponse';
import { Configuration } from '../configuration';
import { COLLECTION_FORMATS } from '../variables';
import { DefaultServiceInterface } from './default.serviceInterface';

/**
 * Request parameters for apiPhpGet operation in DefaultService.
 * @export
 * @interface DefaultServiceApiPhpGetRequest
 */
export interface DefaultServiceApiPhpGetRequest {
    /**
     * Имя действия.
     * @type {string}
     * @memberof DefaultServiceApiPhpGet
     */
    readonly action: string

    /**
     * Имя SQLite-файла (по умолчанию songs.sqlite).
     * @type {string}
     * @memberof DefaultServiceApiPhpGet
     */
    readonly db?: string
}

/**
 * Request parameters for apiPhpactionauthLoginPost operation in DefaultService.
 * @export
 * @interface DefaultServiceApiPhpactionauthLoginPostRequest
 */
export interface DefaultServiceApiPhpactionauthLoginPostRequest {
    /**
     * 
     * @type {ApiPhpActionAuthLoginPostRequest}
     * @memberof DefaultServiceApiPhpactionauthLoginPost
     */
    readonly 'ApiPhpActionAuthLoginPostRequest': ApiPhpActionAuthLoginPostRequest
}

/**
 * Request parameters for apiPhpactionbookVersionsCheckPost operation in DefaultService.
 * @export
 * @interface DefaultServiceApiPhpactionbookVersionsCheckPostRequest
 */
export interface DefaultServiceApiPhpactionbookVersionsCheckPostRequest {
    /**
     * 
     * @type {BookVersionsCheckRequest}
     * @memberof DefaultServiceApiPhpactionbookVersionsCheckPost
     */
    readonly 'BookVersionsCheckRequest': BookVersionsCheckRequest
}

/**
 * Request parameters for apiPhpactiondbDeletePost operation in DefaultService.
 * @export
 * @interface DefaultServiceApiPhpactiondbDeletePostRequest
 */
export interface DefaultServiceApiPhpactiondbDeletePostRequest {
    /**
     * Имя SQLite-файла (например songs.sqlite)
     * @type {string}
     * @memberof DefaultServiceApiPhpactiondbDeletePost
     */
    readonly db: string
}

/**
 * Request parameters for apiPhpactiondownloadDbGet operation in DefaultService.
 * @export
 * @interface DefaultServiceApiPhpactiondownloadDbGetRequest
 */
export interface DefaultServiceApiPhpactiondownloadDbGetRequest {
    /**
     * 
     * @type {string}
     * @memberof DefaultServiceApiPhpactiondownloadDbGet
     */
    readonly db: string
}

/**
 * Request parameters for apiPhpactionexportBookGet operation in DefaultService.
 * @export
 * @interface DefaultServiceApiPhpactionexportBookGetRequest
 */
export interface DefaultServiceApiPhpactionexportBookGetRequest {
    /**
     * Имя SQLite-файла (по умолчанию songs.sqlite)
     * @type {string}
     * @memberof DefaultServiceApiPhpactionexportBookGet
     */
    readonly db?: string

    /**
     * Ключ книги (song_books.file_key). Если в song_books несколько книг и параметр не указан, вернётся ошибка с перечнем доступных ключей. 
     * @type {string}
     * @memberof DefaultServiceApiPhpactionexportBookGet
     */
    readonly fileKey?: string
}

/**
 * Request parameters for apiPhpactionsongDeletePost operation in DefaultService.
 * @export
 * @interface DefaultServiceApiPhpactionsongDeletePostRequest
 */
export interface DefaultServiceApiPhpactionsongDeletePostRequest {
    /**
     * 
     * @type {string}
     * @memberof DefaultServiceApiPhpactionsongDeletePost
     */
    readonly db?: string

    /**
     * 
     * @type {number}
     * @memberof DefaultServiceApiPhpactionsongDeletePost
     */
    readonly id?: number

    /**
     * 
     * @type {number}
     * @memberof DefaultServiceApiPhpactionsongDeletePost
     */
    readonly 'id'?: number
}

/**
 * Request parameters for apiPhpactionsongGetGet operation in DefaultService.
 * @export
 * @interface DefaultServiceApiPhpactionsongGetGetRequest
 */
export interface DefaultServiceApiPhpactionsongGetGetRequest {
    /**
     * 
     * @type {number}
     * @memberof DefaultServiceApiPhpactionsongGetGet
     */
    readonly id: number

    /**
     * 
     * @type {string}
     * @memberof DefaultServiceApiPhpactionsongGetGet
     */
    readonly db?: string
}

/**
 * Request parameters for apiPhpactionsongSavePost operation in DefaultService.
 * @export
 * @interface DefaultServiceApiPhpactionsongSavePostRequest
 */
export interface DefaultServiceApiPhpactionsongSavePostRequest {
    /**
     * 
     * @type {SongSaveRequest}
     * @memberof DefaultServiceApiPhpactionsongSavePost
     */
    readonly 'SongSaveRequest': SongSaveRequest

    /**
     * 
     * @type {string}
     * @memberof DefaultServiceApiPhpactionsongSavePost
     */
    readonly db?: string
}

/**
 * Request parameters for apiPhpactionsongSearchGet operation in DefaultService.
 * @export
 * @interface DefaultServiceApiPhpactionsongSearchGetRequest
 */
export interface DefaultServiceApiPhpactionsongSearchGetRequest {
    /**
     * Имя БД (по умолчанию songs.sqlite)
     * @type {string}
     * @memberof DefaultServiceApiPhpactionsongSearchGet
     */
    readonly db?: string

    /**
     * Поиск по title/author/ref/category
     * @type {string}
     * @memberof DefaultServiceApiPhpactionsongSearchGet
     */
    readonly query?: string

    /**
     * Точный номер песни
     * @type {number}
     * @memberof DefaultServiceApiPhpactionsongSearchGet
     */
    readonly number?: number

    /**
     * 
     * @type {number}
     * @memberof DefaultServiceApiPhpactionsongSearchGet
     */
    readonly page?: number

    /**
     * 
     * @type {number}
     * @memberof DefaultServiceApiPhpactionsongSearchGet
     */
    readonly pageSize?: number

    /**
     * 1 — вернуть полные объекты песен с lyrics
     * @type {0 | 1}
     * @memberof DefaultServiceApiPhpactionsongSearchGet
     */
    readonly includeLyrics?: 0 | 1
}


@Injectable()
export class DefaultService implements DefaultServiceInterface {

    protected basePath = 'https://kantelers.ru/api';
    public defaultHeaders: Record<string,string> = {};
    public configuration = new Configuration();
    protected httpClient: HttpService;

    constructor(httpClient: HttpService, @Optional() configuration: Configuration) {
        this.configuration = configuration || this.configuration;
        this.basePath = configuration?.basePath || this.basePath;
        this.httpClient = configuration?.httpClient || httpClient;
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        return consumes.includes(form);
    }

    /**
     * API router
     * Все действия задаются через query-параметр &#x60;action&#x60;. 
     * @param {DefaultServiceApiPhpGetRequest} requestParameters Request parameters.
     * @param {*} [apiPhpGetOpts.config] Override http request option.
     */
    public apiPhpGet(requestParameters: DefaultServiceApiPhpGetRequest, apiPhpGetOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<any>>;
    public apiPhpGet(requestParameters: DefaultServiceApiPhpGetRequest, apiPhpGetOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        const {
            action,
            db,
        } = requestParameters;

        if (action === null || action === undefined) {
            throw new Error('Required parameter action was null or undefined when calling apiPhpGet.');
        }

        let queryParameters = new URLSearchParams();
        if (action !== undefined && action !== null) {
            queryParameters.append('action', <any>action);
        }
        if (db !== undefined && db !== null) {
            queryParameters.append('db', <any>db);
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<any>(`${this.basePath}/api.php`,
                    {
                        params: queryParameters,
                        withCredentials: this.configuration.withCredentials,
                        ...apiPhpGetOpts?.config,
                        headers: {...headers, ...apiPhpGetOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * Авторизация по email, выдача токена
     * Создаёт/обновляет пользователя и устройство, возвращает токен сессии. Поддерживает JSON (&#x60;application/json&#x60;) и form-urlencoded (&#x60;application/x-www-form-urlencoded&#x60;). 
     * @param {DefaultServiceApiPhpactionauthLoginPostRequest} requestParameters Request parameters.
     * @param {*} [apiPhpactionauthLoginPostOpts.config] Override http request option.
     */
    public apiPhpactionauthLoginPost(requestParameters: DefaultServiceApiPhpactionauthLoginPostRequest, apiPhpactionauthLoginPostOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<AuthResponse>>;
    public apiPhpactionauthLoginPost(requestParameters: DefaultServiceApiPhpactionauthLoginPostRequest, apiPhpactionauthLoginPostOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        const {
            'ApiPhpActionAuthLoginPostRequest': apiPhpActionAuthLoginPostRequest,
        } = requestParameters;

        if (apiPhpActionAuthLoginPostRequest === null || apiPhpActionAuthLoginPostRequest === undefined) {
            throw new Error('Required parameter apiPhpActionAuthLoginPostRequest was null or undefined when calling apiPhpactionauthLoginPost.');
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'application/x-www-form-urlencoded'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.post<AuthResponse>(`${this.basePath}/api.php?action=auth.login`,
                    apiPhpActionAuthLoginPostRequest,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...apiPhpactionauthLoginPostOpts?.config,
                        headers: {...headers, ...apiPhpactionauthLoginPostOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * Проверить, какие справочники (книги) свежее на сервере
     * Если в теле запроса не передан массив books или он пустой, возвращает все доступные справочники с их версиями. Иначе клиент присылает массив книг (song_books.file_key) и их локальных версий, а сервер возвращает список книг, у которых версия на сервере больше. Для каждой такой книги возвращается ссылка для скачивания (экспорт в JSON). Книги ищутся во всех доступных SQLite файлах по fileKey. 
     * @param {DefaultServiceApiPhpactionbookVersionsCheckPostRequest} requestParameters Request parameters.
     * @param {*} [apiPhpactionbookVersionsCheckPostOpts.config] Override http request option.
     */
    public apiPhpactionbookVersionsCheckPost(requestParameters: DefaultServiceApiPhpactionbookVersionsCheckPostRequest, apiPhpactionbookVersionsCheckPostOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<ApiPhpActionBookVersionsCheckPost200Response>>;
    public apiPhpactionbookVersionsCheckPost(requestParameters: DefaultServiceApiPhpactionbookVersionsCheckPostRequest, apiPhpactionbookVersionsCheckPostOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        const {
            'BookVersionsCheckRequest': bookVersionsCheckRequest,
        } = requestParameters;

        if (bookVersionsCheckRequest === null || bookVersionsCheckRequest === undefined) {
            throw new Error('Required parameter bookVersionsCheckRequest was null or undefined when calling apiPhpactionbookVersionsCheckPost.');
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.post<ApiPhpActionBookVersionsCheckPost200Response>(`${this.basePath}/api.php?action=book.versions.check`,
                    bookVersionsCheckRequest,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...apiPhpactionbookVersionsCheckPostOpts?.config,
                        headers: {...headers, ...apiPhpactionbookVersionsCheckPostOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * Удалить SQLite-файл и связанные служебные файлы
     * 
     * @param {DefaultServiceApiPhpactiondbDeletePostRequest} requestParameters Request parameters.
     * @param {*} [apiPhpactiondbDeletePostOpts.config] Override http request option.
     */
    public apiPhpactiondbDeletePost(requestParameters: DefaultServiceApiPhpactiondbDeletePostRequest, apiPhpactiondbDeletePostOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<ApiPhpActionDbDeletePost200Response>>;
    public apiPhpactiondbDeletePost(requestParameters: DefaultServiceApiPhpactiondbDeletePostRequest, apiPhpactiondbDeletePostOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        const {
            db,
        } = requestParameters;

        if (db === null || db === undefined) {
            throw new Error('Required parameter db was null or undefined when calling apiPhpactiondbDeletePost.');
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/x-www-form-urlencoded'
        ];

        const canConsumeForm = this.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): void; };
        let useForm = false;
        let convertFormParamsToString = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            // formParams = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        }

        if (db !== undefined) {
            formParams!.append('db', <any>db);
        }

        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.post<ApiPhpActionDbDeletePost200Response>(`${this.basePath}/api.php?action=db.delete`,
                    convertFormParamsToString ? formParams!.toString() : formParams!,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...apiPhpactiondbDeletePostOpts?.config,
                        headers: {...headers, ...apiPhpactiondbDeletePostOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * Скачать SQLite-файл (требует авторизации)
     * 
     * @param {DefaultServiceApiPhpactiondownloadDbGetRequest} requestParameters Request parameters.
     * @param {*} [apiPhpactiondownloadDbGetOpts.config] Override http request option.
     */
    public apiPhpactiondownloadDbGet(requestParameters: DefaultServiceApiPhpactiondownloadDbGetRequest, apiPhpactiondownloadDbGetOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<Blob>>;
    public apiPhpactiondownloadDbGet(requestParameters: DefaultServiceApiPhpactiondownloadDbGetRequest, apiPhpactiondownloadDbGetOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        const {
            db,
        } = requestParameters;

        if (db === null || db === undefined) {
            throw new Error('Required parameter db was null or undefined when calling apiPhpactiondownloadDbGet.');
        }

        let queryParameters = new URLSearchParams();
        if (db !== undefined && db !== null) {
            queryParameters.append('db', <any>db);
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/octet-stream'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get(`${this.basePath}/api.php?action=download.db`,
                    {
                        params: queryParameters,
                        responseType: "blob",
                        withCredentials: this.configuration.withCredentials,
                        ...apiPhpactiondownloadDbGetOpts?.config,
                        headers: {...headers, ...apiPhpactiondownloadDbGetOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * Экспорт книги песен в JSON (требует авторизации)
     * Возвращает структуру ISongBook на основе SQLite-базы, включая метаданные книги. Требует авторизацию. Если параметр &#x60;fileKey&#x60; не указан, а в БД только одна книга, она будет выбрана автоматически. Иначе &#x60;fileKey&#x60; обязателен. 
     * @param {DefaultServiceApiPhpactionexportBookGetRequest} requestParameters Request parameters.
     * @param {*} [apiPhpactionexportBookGetOpts.config] Override http request option.
     */
    public apiPhpactionexportBookGet(requestParameters: DefaultServiceApiPhpactionexportBookGetRequest, apiPhpactionexportBookGetOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<SongBookExport>>;
    public apiPhpactionexportBookGet(requestParameters: DefaultServiceApiPhpactionexportBookGetRequest, apiPhpactionexportBookGetOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        const {
            db,
            fileKey,
        } = requestParameters;

        let queryParameters = new URLSearchParams();
        if (db !== undefined && db !== null) {
            queryParameters.append('db', <any>db);
        }
        if (fileKey !== undefined && fileKey !== null) {
            queryParameters.append('fileKey', <any>fileKey);
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<SongBookExport>(`${this.basePath}/api.php?action=exportBook`,
                    {
                        params: queryParameters,
                        withCredentials: this.configuration.withCredentials,
                        ...apiPhpactionexportBookGetOpts?.config,
                        headers: {...headers, ...apiPhpactionexportBookGetOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * Проверка доступности API
     * 
     * @param {*} [apiPhpactionpingGetOpts.config] Override http request option.
     */
    public apiPhpactionpingGet(apiPhpactionpingGetOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<ApiPhpActionPingGet200Response>>;
    public apiPhpactionpingGet(apiPhpactionpingGetOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<ApiPhpActionPingGet200Response>(`${this.basePath}/api.php?action=ping`,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...apiPhpactionpingGetOpts?.config,
                        headers: {...headers, ...apiPhpactionpingGetOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * Список SQLite-справочников
     * 
     * @param {*} [apiPhpactionregistryListGetOpts.config] Override http request option.
     */
    public apiPhpactionregistryListGet(apiPhpactionregistryListGetOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<ApiPhpActionRegistryListGet200Response>>;
    public apiPhpactionregistryListGet(apiPhpactionregistryListGetOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<ApiPhpActionRegistryListGet200Response>(`${this.basePath}/api.php?action=registry.list`,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...apiPhpactionregistryListGetOpts?.config,
                        headers: {...headers, ...apiPhpactionregistryListGetOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * Удалить песню
     * 
     * @param {DefaultServiceApiPhpactionsongDeletePostRequest} requestParameters Request parameters.
     * @param {*} [apiPhpactionsongDeletePostOpts.config] Override http request option.
     */
    public apiPhpactionsongDeletePost(requestParameters: DefaultServiceApiPhpactionsongDeletePostRequest, apiPhpactionsongDeletePostOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<ApiPhpActionSongSavePost200Response>>;
    public apiPhpactionsongDeletePost(requestParameters: DefaultServiceApiPhpactionsongDeletePostRequest, apiPhpactionsongDeletePostOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        const {
            db,
            id,
            'id': id2,
        } = requestParameters;

        let queryParameters = new URLSearchParams();
        if (db !== undefined && db !== null) {
            queryParameters.append('db', <any>db);
        }
        if (id !== undefined && id !== null) {
            queryParameters.append('id', <any>id);
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/x-www-form-urlencoded'
        ];

        const canConsumeForm = this.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): void; };
        let useForm = false;
        let convertFormParamsToString = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            // formParams = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        }

        if (id2 !== undefined) {
            formParams!.append('id', <any>id2);
        }

        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.post<ApiPhpActionSongSavePost200Response>(`${this.basePath}/api.php?action=song.delete`,
                    convertFormParamsToString ? formParams!.toString() : formParams!,
                    {
                        params: queryParameters,
                        withCredentials: this.configuration.withCredentials,
                        ...apiPhpactionsongDeletePostOpts?.config,
                        headers: {...headers, ...apiPhpactionsongDeletePostOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * Получить одну песню (полную)
     * 
     * @param {DefaultServiceApiPhpactionsongGetGetRequest} requestParameters Request parameters.
     * @param {*} [apiPhpactionsongGetGetOpts.config] Override http request option.
     */
    public apiPhpactionsongGetGet(requestParameters: DefaultServiceApiPhpactionsongGetGetRequest, apiPhpactionsongGetGetOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<ApiPhpActionSongGetGet200Response>>;
    public apiPhpactionsongGetGet(requestParameters: DefaultServiceApiPhpactionsongGetGetRequest, apiPhpactionsongGetGetOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        const {
            id,
            db,
        } = requestParameters;

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling apiPhpactionsongGetGet.');
        }

        let queryParameters = new URLSearchParams();
        if (db !== undefined && db !== null) {
            queryParameters.append('db', <any>db);
        }
        if (id !== undefined && id !== null) {
            queryParameters.append('id', <any>id);
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<ApiPhpActionSongGetGet200Response>(`${this.basePath}/api.php?action=song.get`,
                    {
                        params: queryParameters,
                        withCredentials: this.configuration.withCredentials,
                        ...apiPhpactionsongGetGetOpts?.config,
                        headers: {...headers, ...apiPhpactionsongGetGetOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * Создание или обновление песни
     * 
     * @param {DefaultServiceApiPhpactionsongSavePostRequest} requestParameters Request parameters.
     * @param {*} [apiPhpactionsongSavePostOpts.config] Override http request option.
     */
    public apiPhpactionsongSavePost(requestParameters: DefaultServiceApiPhpactionsongSavePostRequest, apiPhpactionsongSavePostOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<ApiPhpActionSongSavePost200Response>>;
    public apiPhpactionsongSavePost(requestParameters: DefaultServiceApiPhpactionsongSavePostRequest, apiPhpactionsongSavePostOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        const {
            'SongSaveRequest': songSaveRequest,
            db,
        } = requestParameters;

        if (songSaveRequest === null || songSaveRequest === undefined) {
            throw new Error('Required parameter songSaveRequest was null or undefined when calling apiPhpactionsongSavePost.');
        }

        let queryParameters = new URLSearchParams();
        if (db !== undefined && db !== null) {
            queryParameters.append('db', <any>db);
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.post<ApiPhpActionSongSavePost200Response>(`${this.basePath}/api.php?action=song.save`,
                    songSaveRequest,
                    {
                        params: queryParameters,
                        withCredentials: this.configuration.withCredentials,
                        ...apiPhpactionsongSavePostOpts?.config,
                        headers: {...headers, ...apiPhpactionsongSavePostOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * Поиск песен
     * 
     * @param {DefaultServiceApiPhpactionsongSearchGetRequest} requestParameters Request parameters.
     * @param {*} [apiPhpactionsongSearchGetOpts.config] Override http request option.
     */
    public apiPhpactionsongSearchGet(requestParameters: DefaultServiceApiPhpactionsongSearchGetRequest, apiPhpactionsongSearchGetOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<SongSearchResponse>>;
    public apiPhpactionsongSearchGet(requestParameters: DefaultServiceApiPhpactionsongSearchGetRequest, apiPhpactionsongSearchGetOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        const {
            db,
            query,
            number,
            page,
            pageSize,
            includeLyrics,
        } = requestParameters;

        let queryParameters = new URLSearchParams();
        if (db !== undefined && db !== null) {
            queryParameters.append('db', <any>db);
        }
        if (query !== undefined && query !== null) {
            queryParameters.append('query', <any>query);
        }
        if (number !== undefined && number !== null) {
            queryParameters.append('number', <any>number);
        }
        if (page !== undefined && page !== null) {
            queryParameters.append('page', <any>page);
        }
        if (pageSize !== undefined && pageSize !== null) {
            queryParameters.append('pageSize', <any>pageSize);
        }
        if (includeLyrics !== undefined && includeLyrics !== null) {
            queryParameters.append('includeLyrics', <any>includeLyrics);
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearerAuth) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<SongSearchResponse>(`${this.basePath}/api.php?action=song.search`,
                    {
                        params: queryParameters,
                        withCredentials: this.configuration.withCredentials,
                        ...apiPhpactionsongSearchGetOpts?.config,
                        headers: {...headers, ...apiPhpactionsongSearchGetOpts?.config?.headers},
                    }
                );
            })
        );
    }
}
