/**
 * Lyricast Dictionary API
 * API для работы со справочниками песен/Библии на основе SQLite
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Observable }                                        from 'rxjs';

import { ApiPhpActionAuthLoginPostRequest } from '../models/apiPhpActionAuthLoginPostRequest';
import { ApiPhpActionBookVersionsCheckPost200Response } from '../models/apiPhpActionBookVersionsCheckPost200Response';
import { ApiPhpActionDbDeletePost200Response } from '../models/apiPhpActionDbDeletePost200Response';
import { ApiPhpActionExportBookGet400Response } from '../models/apiPhpActionExportBookGet400Response';
import { ApiPhpActionExportBookGet404Response } from '../models/apiPhpActionExportBookGet404Response';
import { ApiPhpActionPingGet200Response } from '../models/apiPhpActionPingGet200Response';
import { ApiPhpActionRegistryListGet200Response } from '../models/apiPhpActionRegistryListGet200Response';
import { ApiPhpActionSongGetGet200Response } from '../models/apiPhpActionSongGetGet200Response';
import { ApiPhpActionSongSavePost200Response } from '../models/apiPhpActionSongSavePost200Response';
import { AuthResponse } from '../models/authResponse';
import { BookVersionsCheckRequest } from '../models/bookVersionsCheckRequest';
import { SongBookExport } from '../models/songBookExport';
import { SongSaveRequest } from '../models/songSaveRequest';
import { SongSearchResponse } from '../models/songSearchResponse';


import { Configuration }                                     from '../configuration';


export interface DefaultServiceInterface {
    defaultHeaders: {};
    configuration: Configuration;

    /**
    * API router
    * Все действия задаются через query-параметр &#x60;action&#x60;. 
    * @param action Имя действия.
    * @param db Имя SQLite-файла (по умолчанию songs.sqlite).
    */
    apiPhpGet(action: string, db?: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
    * Авторизация по email, выдача токена
    * Создаёт/обновляет пользователя и устройство, возвращает токен сессии. Поддерживает JSON (&#x60;application/json&#x60;) и form-urlencoded (&#x60;application/x-www-form-urlencoded&#x60;). 
    * @param apiPhpActionAuthLoginPostRequest 
    */
    apiPhpactionauthLoginPost(apiPhpActionAuthLoginPostRequest: ApiPhpActionAuthLoginPostRequest, extraHttpRequestParams?: any): Observable<AuthResponse>;

    /**
    * Проверить, какие справочники (книги) свежее на сервере
    * Если в теле запроса не передан массив books или он пустой, возвращает все доступные справочники с их версиями. Иначе клиент присылает массив книг (song_books.file_key) и их локальных версий, а сервер возвращает список книг, у которых версия на сервере больше. Для каждой такой книги возвращается ссылка для скачивания (экспорт в JSON). 
    * @param bookVersionsCheckRequest 
    */
    apiPhpactionbookVersionsCheckPost(bookVersionsCheckRequest: BookVersionsCheckRequest, extraHttpRequestParams?: any): Observable<ApiPhpActionBookVersionsCheckPost200Response>;

    /**
    * Удалить SQLite-файл и связанные служебные файлы
    * 
    * @param db Имя SQLite-файла (например songs.sqlite)
    */
    apiPhpactiondbDeletePost(db: string, extraHttpRequestParams?: any): Observable<ApiPhpActionDbDeletePost200Response>;

    /**
    * Скачать SQLite-файл (требует авторизации)
    * 
    * @param db 
    */
    apiPhpactiondownloadDbGet(db: string, extraHttpRequestParams?: any): Observable<Blob>;

    /**
    * Экспорт книги песен в JSON (требует авторизации)
    * Возвращает структуру ISongBook на основе SQLite-базы, включая метаданные книги. Требует авторизацию. Если параметр &#x60;fileKey&#x60; не указан, а в БД только одна книга, она будет выбрана автоматически. Иначе &#x60;fileKey&#x60; обязателен. 
    * @param db Имя SQLite-файла (по умолчанию songs.sqlite)
    * @param fileKey Ключ книги (song_books.file_key). Если в song_books несколько книг и параметр не указан, вернётся ошибка с перечнем доступных ключей. 
    */
    apiPhpactionexportBookGet(db?: string, fileKey?: string, extraHttpRequestParams?: any): Observable<SongBookExport>;

    /**
    * Проверка доступности API
    * 
    */
    apiPhpactionpingGet(extraHttpRequestParams?: any): Observable<ApiPhpActionPingGet200Response>;

    /**
    * Список SQLite-справочников
    * 
    */
    apiPhpactionregistryListGet(extraHttpRequestParams?: any): Observable<ApiPhpActionRegistryListGet200Response>;

    /**
    * Удалить песню
    * 
    * @param db 
    * @param id 
    * @param id2 
    */
    apiPhpactionsongDeletePost(db?: string, id?: number, id2?: number, extraHttpRequestParams?: any): Observable<ApiPhpActionSongSavePost200Response>;

    /**
    * Получить одну песню (полную)
    * 
    * @param id 
    * @param db 
    */
    apiPhpactionsongGetGet(id: number, db?: string, extraHttpRequestParams?: any): Observable<ApiPhpActionSongGetGet200Response>;

    /**
    * Создание или обновление песни
    * 
    * @param songSaveRequest 
    * @param db 
    */
    apiPhpactionsongSavePost(songSaveRequest: SongSaveRequest, db?: string, extraHttpRequestParams?: any): Observable<ApiPhpActionSongSavePost200Response>;

    /**
    * Поиск песен
    * 
    * @param db Имя БД (по умолчанию songs.sqlite)
    * @param query Поиск по title/author/ref/category
    * @param number Точный номер песни
    * @param page 
    * @param pageSize 
    * @param includeLyrics 1 — вернуть полные объекты песен с lyrics
    */
    apiPhpactionsongSearchGet(db?: string, query?: string, number?: number, page?: number, pageSize?: number, includeLyrics?: 0 | 1, extraHttpRequestParams?: any): Observable<SongSearchResponse>;

}
