// @ts-nocheck
/**
 * Dictionary API
 * API for dictionaries (songs, bibles, programs)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Observable }                                        from 'rxjs';

import { AppControllerPing200Response } from '../model/appControllerPing200Response';


import { Configuration }                                     from '../configuration';


export interface HealthServiceInterface {
    defaultHeaders: {};
    configuration: Configuration;

    /**
    * Проверка доступности API
    * 
    */
    appControllerPing(extraHttpRequestParams?: any): Observable<AppControllerPing200Response>;

}
