// @ts-nocheck
/**
 * Dictionary API
 * API for dictionaries (songs, bibles, programs)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Injectable, Optional } from '@nestjs/common';
import { HttpService } from '@nestjs/axios';
import type { AxiosRequestConfig, AxiosResponse } from 'axios';
import { Observable, from, of, switchMap } from 'rxjs';
import { AppControllerPing200Response } from '../model/appControllerPing200Response';
import { Configuration } from '../configuration';
import { COLLECTION_FORMATS } from '../variables';
import { HealthServiceInterface } from './health.serviceInterface';


@Injectable()
export class HealthService implements HealthServiceInterface {

    protected basePath = 'http://localhost';
    public defaultHeaders: Record<string,string> = {};
    public configuration = new Configuration();
    protected httpClient: HttpService;

    constructor(httpClient: HttpService, @Optional() configuration: Configuration) {
        this.configuration = configuration || this.configuration;
        this.basePath = configuration?.basePath || this.basePath;
        this.httpClient = configuration?.httpClient || httpClient;
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        return consumes.includes(form);
    }

    /**
     * Проверка доступности API
     * 
     * @param {*} [appControllerPingOpts.config] Override http request option.
     */
    public appControllerPing(appControllerPingOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<AppControllerPing200Response>>;
    public appControllerPing(appControllerPingOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<AppControllerPing200Response>(`${this.basePath}/api/ping`,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...appControllerPingOpts?.config,
                        headers: {...headers, ...appControllerPingOpts?.config?.headers},
                    }
                );
            })
        );
    }
}
