// @ts-nocheck
/**
 * Dictionary API
 * API for dictionaries (songs, bibles, programs)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Observable }                                        from 'rxjs';

import { CreateSongBookDto } from '../model/createSongBookDto';
import { CreateSongDto } from '../model/createSongDto';
import { ImportSongBookDto } from '../model/importSongBookDto';
import { RegistryResponseDto } from '../model/registryResponseDto';
import { SongBookExportDto } from '../model/songBookExportDto';
import { UpdateSongDto } from '../model/updateSongDto';
import { VersionsCheckRequestDto } from '../model/versionsCheckRequestDto';
import { VersionsCheckResponseDto } from '../model/versionsCheckResponseDto';


import { Configuration }                                     from '../configuration';


export interface SongsServiceInterface {
    defaultHeaders: {};
    configuration: Configuration;

    /**
    * Проверить, какие книги новее на сервере
    * 
    * @param versionsCheckRequestDto 
    */
    songsControllerCheckVersions(versionsCheckRequestDto: VersionsCheckRequestDto, extraHttpRequestParams?: any): Observable<VersionsCheckResponseDto>;

    /**
    * Создание песни
    * 
    * @param createSongDto 
    */
    songsControllerCreate(createSongDto: CreateSongDto, extraHttpRequestParams?: any): Observable<{}>;

    /**
    * Создать пустой SongBook без импорта JSON
    * 
    * @param createSongBookDto 
    */
    songsControllerCreateSongBook(createSongBookDto: CreateSongBookDto, extraHttpRequestParams?: any): Observable<{}>;

    /**
    * Экспорт книги песен в JSON (SongBookExport)
    * 
    * @param songBookId 
    */
    songsControllerExportSongBook(songBookId: number, extraHttpRequestParams?: any): Observable<SongBookExportDto>;

    /**
    * Список песен по сборнику
    * 
    * @param songBookId 
    * @param q 
    * @param page 
    * @param pageSize 
    */
    songsControllerFindAll(songBookId: number, q?: string, page?: number, pageSize?: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
    * Получить песню
    * 
    * @param id 
    */
    songsControllerFindOne(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
    * Импорт SongBook из JSON в PostgreSQL
    * 
    * @param importSongBookDto 
    */
    songsControllerImportSongBook(importSongBookDto: ImportSongBookDto, extraHttpRequestParams?: any): Observable<{}>;

    /**
    * Реестр сборников (registry.list)
    * 
    */
    songsControllerRegistry(extraHttpRequestParams?: any): Observable<RegistryResponseDto>;

    /**
    * Удалить песню
    * 
    * @param id 
    */
    songsControllerRemove(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
    * Обновить песню
    * 
    * @param id 
    * @param updateSongDto 
    */
    songsControllerUpdate(id: number, updateSongDto: UpdateSongDto, extraHttpRequestParams?: any): Observable<{}>;

    /**
    * Обновить мета-информацию сборника (song_book_meta)
    * 
    * @param songBookId 
    * @param body 
    */
    songsControllerUpdateSongBookMeta(songBookId: number, body: object, extraHttpRequestParams?: any): Observable<{}>;

}
