// @ts-nocheck
/**
 * Dictionary API
 * API for dictionaries (songs, bibles, programs)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Injectable, Optional } from '@nestjs/common';
import { HttpService } from '@nestjs/axios';
import type { AxiosRequestConfig, AxiosResponse } from 'axios';
import { Observable, from, of, switchMap } from 'rxjs';
import { CreateSongBookDto } from '../model/createSongBookDto';
import { CreateSongDto } from '../model/createSongDto';
import { ImportSongBookDto } from '../model/importSongBookDto';
import { RegistryResponseDto } from '../model/registryResponseDto';
import { SongBookExportDto } from '../model/songBookExportDto';
import { UpdateSongDto } from '../model/updateSongDto';
import { VersionsCheckRequestDto } from '../model/versionsCheckRequestDto';
import { VersionsCheckResponseDto } from '../model/versionsCheckResponseDto';
import { Configuration } from '../configuration';
import { COLLECTION_FORMATS } from '../variables';
import { SongsServiceInterface } from './songs.serviceInterface';

/**
 * Request parameters for songsControllerCheckVersions operation in SongsService.
 * @export
 * @interface SongsServiceSongsControllerCheckVersionsRequest
 */
export interface SongsServiceSongsControllerCheckVersionsRequest {
    /**
     *
     * @type {VersionsCheckRequestDto}
     * @memberof SongsServiceSongsControllerCheckVersions
     */
    readonly 'VersionsCheckRequestDto': VersionsCheckRequestDto
}

/**
 * Request parameters for songsControllerCreate operation in SongsService.
 * @export
 * @interface SongsServiceSongsControllerCreateRequest
 */
export interface SongsServiceSongsControllerCreateRequest {
    /**
     *
     * @type {CreateSongDto}
     * @memberof SongsServiceSongsControllerCreate
     */
    readonly 'CreateSongDto': CreateSongDto
}

/**
 * Request parameters for songsControllerCreateSongBook operation in SongsService.
 * @export
 * @interface SongsServiceSongsControllerCreateSongBookRequest
 */
export interface SongsServiceSongsControllerCreateSongBookRequest {
    /**
     *
     * @type {CreateSongBookDto}
     * @memberof SongsServiceSongsControllerCreateSongBook
     */
    readonly 'CreateSongBookDto': CreateSongBookDto
}

/**
 * Request parameters for songsControllerExportSongBook operation in SongsService.
 * @export
 * @interface SongsServiceSongsControllerExportSongBookRequest
 */
export interface SongsServiceSongsControllerExportSongBookRequest {
    /**
     *
     * @type {number}
     * @memberof SongsServiceSongsControllerExportSongBook
     */
    readonly songBookId: number
}

/**
 * Request parameters for songsControllerFindAll operation in SongsService.
 * @export
 * @interface SongsServiceSongsControllerFindAllRequest
 */
export interface SongsServiceSongsControllerFindAllRequest {
    /**
     *
     * @type {number}
     * @memberof SongsServiceSongsControllerFindAll
     */
    readonly songBookId: number

    /**
     *
     * @type {string}
     * @memberof SongsServiceSongsControllerFindAll
     */
    readonly q?: string

    /**
     *
     * @type {number}
     * @memberof SongsServiceSongsControllerFindAll
     */
    readonly page?: number

    /**
     *
     * @type {number}
     * @memberof SongsServiceSongsControllerFindAll
     */
    readonly pageSize?: number
}

/**
 * Request parameters for songsControllerFindOne operation in SongsService.
 * @export
 * @interface SongsServiceSongsControllerFindOneRequest
 */
export interface SongsServiceSongsControllerFindOneRequest {
    /**
     *
     * @type {number}
     * @memberof SongsServiceSongsControllerFindOne
     */
    readonly id: number
}

/**
 * Request parameters for songsControllerImportSongBook operation in SongsService.
 * @export
 * @interface SongsServiceSongsControllerImportSongBookRequest
 */
export interface SongsServiceSongsControllerImportSongBookRequest {
    /**
     *
     * @type {ImportSongBookDto}
     * @memberof SongsServiceSongsControllerImportSongBook
     */
    readonly 'ImportSongBookDto': ImportSongBookDto
}

/**
 * Request parameters for songsControllerRemove operation in SongsService.
 * @export
 * @interface SongsServiceSongsControllerRemoveRequest
 */
export interface SongsServiceSongsControllerRemoveRequest {
    /**
     *
     * @type {number}
     * @memberof SongsServiceSongsControllerRemove
     */
    readonly id: number
}

/**
 * Request parameters for songsControllerUpdate operation in SongsService.
 * @export
 * @interface SongsServiceSongsControllerUpdateRequest
 */
export interface SongsServiceSongsControllerUpdateRequest {
    /**
     *
     * @type {number}
     * @memberof SongsServiceSongsControllerUpdate
     */
    readonly id: number

    /**
     *
     * @type {UpdateSongDto}
     * @memberof SongsServiceSongsControllerUpdate
     */
    readonly 'UpdateSongDto': UpdateSongDto
}

/**
 * Request parameters for songsControllerUpdateSongBookMeta operation in SongsService.
 * @export
 * @interface SongsServiceSongsControllerUpdateSongBookMetaRequest
 */
export interface SongsServiceSongsControllerUpdateSongBookMetaRequest {
    /**
     *
     * @type {number}
     * @memberof SongsServiceSongsControllerUpdateSongBookMeta
     */
    readonly songBookId: number

    /**
     *
     * @type {object}
     * @memberof SongsServiceSongsControllerUpdateSongBookMeta
     */
    readonly body: object
}


@Injectable()
export class SongsService implements SongsServiceInterface {

    // protected basePath = 'http://localhost';
    protected basePath = 'https://lyricast-dictionary-api.onrender.com';
    public defaultHeaders: Record<string,string> = {};
    public configuration = new Configuration();
    protected httpClient: HttpService;

    constructor(httpClient: HttpService, @Optional() configuration: Configuration) {
        this.configuration = configuration || this.configuration;
        this.basePath = configuration?.basePath || this.basePath;
        this.httpClient = configuration?.httpClient || httpClient;
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        return consumes.includes(form);
    }

    /**
     * Проверить, какие книги новее на сервере
     *
     * @param {SongsServiceSongsControllerCheckVersionsRequest} requestParameters Request parameters.
     * @param {*} [songsControllerCheckVersionsOpts.config] Override http request option.
     */
    public songsControllerCheckVersions(requestParameters: SongsServiceSongsControllerCheckVersionsRequest, songsControllerCheckVersionsOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<VersionsCheckResponseDto>>;
    public songsControllerCheckVersions(requestParameters: SongsServiceSongsControllerCheckVersionsRequest, songsControllerCheckVersionsOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        const {
            'VersionsCheckRequestDto': versionsCheckRequestDto,
        } = requestParameters;

        if (versionsCheckRequestDto === null || versionsCheckRequestDto === undefined) {
            throw new Error('Required parameter versionsCheckRequestDto was null or undefined when calling songsControllerCheckVersions.');
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearer) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.post<VersionsCheckResponseDto>(`${this.basePath}/api/songs/versions/check`,
                    versionsCheckRequestDto,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...songsControllerCheckVersionsOpts?.config,
                        headers: {...headers, ...songsControllerCheckVersionsOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * Создание песни
     *
     * @param {SongsServiceSongsControllerCreateRequest} requestParameters Request parameters.
     * @param {*} [songsControllerCreateOpts.config] Override http request option.
     */
    public songsControllerCreate(requestParameters: SongsServiceSongsControllerCreateRequest, songsControllerCreateOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<any>>;
    public songsControllerCreate(requestParameters: SongsServiceSongsControllerCreateRequest, songsControllerCreateOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        const {
            'CreateSongDto': createSongDto,
        } = requestParameters;

        if (createSongDto === null || createSongDto === undefined) {
            throw new Error('Required parameter createSongDto was null or undefined when calling songsControllerCreate.');
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearer) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.post<any>(`${this.basePath}/api/songs`,
                    createSongDto,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...songsControllerCreateOpts?.config,
                        headers: {...headers, ...songsControllerCreateOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * Создать пустой SongBook без импорта JSON
     *
     * @param {SongsServiceSongsControllerCreateSongBookRequest} requestParameters Request parameters.
     * @param {*} [songsControllerCreateSongBookOpts.config] Override http request option.
     */
    public songsControllerCreateSongBook(requestParameters: SongsServiceSongsControllerCreateSongBookRequest, songsControllerCreateSongBookOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<any>>;
    public songsControllerCreateSongBook(requestParameters: SongsServiceSongsControllerCreateSongBookRequest, songsControllerCreateSongBookOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        const {
            'CreateSongBookDto': createSongBookDto,
        } = requestParameters;

        if (createSongBookDto === null || createSongBookDto === undefined) {
            throw new Error('Required parameter createSongBookDto was null or undefined when calling songsControllerCreateSongBook.');
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearer) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.post<any>(`${this.basePath}/api/songs/song-books`,
                    createSongBookDto,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...songsControllerCreateSongBookOpts?.config,
                        headers: {...headers, ...songsControllerCreateSongBookOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * Экспорт книги песен в JSON (SongBookExport)
     *
     * @param {SongsServiceSongsControllerExportSongBookRequest} requestParameters Request parameters.
     * @param {*} [songsControllerExportSongBookOpts.config] Override http request option.
     */
    public songsControllerExportSongBook(requestParameters: SongsServiceSongsControllerExportSongBookRequest, songsControllerExportSongBookOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<SongBookExportDto>>;
    public songsControllerExportSongBook(requestParameters: SongsServiceSongsControllerExportSongBookRequest, songsControllerExportSongBookOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        const {
            songBookId,
        } = requestParameters;

        if (songBookId === null || songBookId === undefined) {
            throw new Error('Required parameter songBookId was null or undefined when calling songsControllerExportSongBook.');
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearer) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<SongBookExportDto>(`${this.basePath}/api/songs/song-books/${encodeURIComponent(String(songBookId))}/export`,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...songsControllerExportSongBookOpts?.config,
                        headers: {...headers, ...songsControllerExportSongBookOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * Список песен по сборнику
     *
     * @param {SongsServiceSongsControllerFindAllRequest} requestParameters Request parameters.
     * @param {*} [songsControllerFindAllOpts.config] Override http request option.
     */
    public songsControllerFindAll(requestParameters: SongsServiceSongsControllerFindAllRequest, songsControllerFindAllOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<any>>;
    public songsControllerFindAll(requestParameters: SongsServiceSongsControllerFindAllRequest, songsControllerFindAllOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        const {
            songBookId,
            q,
            page,
            pageSize,
        } = requestParameters;

        if (songBookId === null || songBookId === undefined) {
            throw new Error('Required parameter songBookId was null or undefined when calling songsControllerFindAll.');
        }

        let queryParameters = new URLSearchParams();
        if (songBookId !== undefined && songBookId !== null) {
            queryParameters.append('songBookId', <any>songBookId);
        }
        if (q !== undefined && q !== null) {
            queryParameters.append('q', <any>q);
        }
        if (page !== undefined && page !== null) {
            queryParameters.append('page', <any>page);
        }
        if (pageSize !== undefined && pageSize !== null) {
            queryParameters.append('pageSize', <any>pageSize);
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearer) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<any>(`${this.basePath}/api/songs`,
                    {
                        params: queryParameters,
                        withCredentials: this.configuration.withCredentials,
                        ...songsControllerFindAllOpts?.config,
                        headers: {...headers, ...songsControllerFindAllOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * Получить песню
     *
     * @param {SongsServiceSongsControllerFindOneRequest} requestParameters Request parameters.
     * @param {*} [songsControllerFindOneOpts.config] Override http request option.
     */
    public songsControllerFindOne(requestParameters: SongsServiceSongsControllerFindOneRequest, songsControllerFindOneOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<any>>;
    public songsControllerFindOne(requestParameters: SongsServiceSongsControllerFindOneRequest, songsControllerFindOneOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        const {
            id,
        } = requestParameters;

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling songsControllerFindOne.');
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearer) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<any>(`${this.basePath}/api/songs/${encodeURIComponent(String(id))}`,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...songsControllerFindOneOpts?.config,
                        headers: {...headers, ...songsControllerFindOneOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * Импорт SongBook из JSON в PostgreSQL
     *
     * @param {SongsServiceSongsControllerImportSongBookRequest} requestParameters Request parameters.
     * @param {*} [songsControllerImportSongBookOpts.config] Override http request option.
     */
    public songsControllerImportSongBook(requestParameters: SongsServiceSongsControllerImportSongBookRequest, songsControllerImportSongBookOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<any>>;
    public songsControllerImportSongBook(requestParameters: SongsServiceSongsControllerImportSongBookRequest, songsControllerImportSongBookOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        const {
            'ImportSongBookDto': importSongBookDto,
        } = requestParameters;

        if (importSongBookDto === null || importSongBookDto === undefined) {
            throw new Error('Required parameter importSongBookDto was null or undefined when calling songsControllerImportSongBook.');
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearer) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.post<any>(`${this.basePath}/api/songs/song-books/import`,
                    importSongBookDto,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...songsControllerImportSongBookOpts?.config,
                        headers: {...headers, ...songsControllerImportSongBookOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * Реестр сборников (registry.list)
     *
     * @param {*} [songsControllerRegistryOpts.config] Override http request option.
     */
    public songsControllerRegistry(songsControllerRegistryOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<RegistryResponseDto>>;
    public songsControllerRegistry(songsControllerRegistryOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearer) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<RegistryResponseDto>(`${this.basePath}/api/songs/registry`,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...songsControllerRegistryOpts?.config,
                        headers: {...headers, ...songsControllerRegistryOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * Удалить песню
     *
     * @param {SongsServiceSongsControllerRemoveRequest} requestParameters Request parameters.
     * @param {*} [songsControllerRemoveOpts.config] Override http request option.
     */
    public songsControllerRemove(requestParameters: SongsServiceSongsControllerRemoveRequest, songsControllerRemoveOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<any>>;
    public songsControllerRemove(requestParameters: SongsServiceSongsControllerRemoveRequest, songsControllerRemoveOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        const {
            id,
        } = requestParameters;

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling songsControllerRemove.');
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearer) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.delete<any>(`${this.basePath}/api/songs/${encodeURIComponent(String(id))}`,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...songsControllerRemoveOpts?.config,
                        headers: {...headers, ...songsControllerRemoveOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * Обновить песню
     *
     * @param {SongsServiceSongsControllerUpdateRequest} requestParameters Request parameters.
     * @param {*} [songsControllerUpdateOpts.config] Override http request option.
     */
    public songsControllerUpdate(requestParameters: SongsServiceSongsControllerUpdateRequest, songsControllerUpdateOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<any>>;
    public songsControllerUpdate(requestParameters: SongsServiceSongsControllerUpdateRequest, songsControllerUpdateOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        const {
            id,
            'UpdateSongDto': updateSongDto,
        } = requestParameters;

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling songsControllerUpdate.');
        }

        if (updateSongDto === null || updateSongDto === undefined) {
            throw new Error('Required parameter updateSongDto was null or undefined when calling songsControllerUpdate.');
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearer) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.put<any>(`${this.basePath}/api/songs/${encodeURIComponent(String(id))}`,
                    updateSongDto,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...songsControllerUpdateOpts?.config,
                        headers: {...headers, ...songsControllerUpdateOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * Обновить мета-информацию сборника (song_book_meta)
     *
     * @param {SongsServiceSongsControllerUpdateSongBookMetaRequest} requestParameters Request parameters.
     * @param {*} [songsControllerUpdateSongBookMetaOpts.config] Override http request option.
     */
    public songsControllerUpdateSongBookMeta(requestParameters: SongsServiceSongsControllerUpdateSongBookMetaRequest, songsControllerUpdateSongBookMetaOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<any>>;
    public songsControllerUpdateSongBookMeta(requestParameters: SongsServiceSongsControllerUpdateSongBookMetaRequest, songsControllerUpdateSongBookMetaOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        const {
            songBookId,
            body,
        } = requestParameters;

        if (songBookId === null || songBookId === undefined) {
            throw new Error('Required parameter songBookId was null or undefined when calling songsControllerUpdateSongBookMeta.');
        }

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling songsControllerUpdateSongBookMeta.');
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearer) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.patch<any>(`${this.basePath}/api/songs/song-books/${encodeURIComponent(String(songBookId))}/meta`,
                    body,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...songsControllerUpdateSongBookMetaOpts?.config,
                        headers: {...headers, ...songsControllerUpdateSongBookMetaOpts?.config?.headers},
                    }
                );
            })
        );
    }
}
