/**
 * Lyricast Dictionary API
 * API для работы со справочниками песен/Библии на основе SQLite
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BookUpdateItem } from './bookUpdateItem';
import { BookVersionsCheckResponse } from './bookVersionsCheckResponse';
import { AllBooksResponseBooksInner } from './allBooksResponseBooksInner';
import { AllBooksResponse } from './allBooksResponse';


/**
 * @type ApiPhpActionBookVersionsCheckPost200Response
 * @export
 */
export type ApiPhpActionBookVersionsCheckPost200Response = AllBooksResponse | BookVersionsCheckResponse;

