// @ts-nocheck
/**
 * Lyricast Dictionary API
 * API для работы со справочниками песен/Библии на основе SQLite
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BookUpdateItem { 
    /**
     * Ключ книги (song_books.file_key)
     */
    fileKey: string;
    /**
     * Версия книги на сервере
     */
    version: number;
    /**
     * URL для скачивания книги (экспорт в JSON)
     */
    downloadUrl: string;
}

