// @ts-nocheck
/**
 * Lyricast Dictionary API
 * API для работы со справочниками песен/Библии на основе SQLite
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BookMetaSaveRequest { 
    /**
     * song_books.file_key, который нужно обновить
     */
    fileKey: string;
    /**
     * Объект ключ-значение, который будет upsert-нут в song_book_meta. Если передан key coverImage (data:URL), сервер автоматически пережмёт изображение до максимального размера 512x512 px. 
     */
    meta?: { [key: string]: string; } | null;
    deleteKeys?: Array<string> | null;
}

