// @ts-nocheck
/**
 * Lyricast Dictionary API
 * API для работы со справочниками песен/Библии на основе SQLite
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BookMetaSaveResponse { 
    ok: boolean;
    db: string;
    fileKey: string;
    /**
     * Ключи, которые были успешно обновлены/созданы
     */
    updatedKeys: Array<string>;
    /**
     * Ключи, которые были удалены
     */
    deletedKeys: Array<string>;
    /**
     * Текущая версия справочника после изменений
     */
    version: number;
}

