/**
 * Lyricast Dictionary API
 * API для работы со справочниками песен/Библии на основе SQLite
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BookVersionItem } from './bookVersionItem';


export interface BookVersionsCheckRequest { 
    /**
     * Массив книг для проверки версий. Если отсутствует или пустой, возвращаются все доступные книги
     */
    books: Array<BookVersionItem>;
}

