// @ts-nocheck
/**
 * Dictionary API
 * API for dictionaries (songs, bibles, programs)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SongBookExportDto } from './songBookExportDto';


export interface ImportSongBookDto { 
    /**
     * ID каталога, в который помещаем сборник
     */
    catalogId: number;
    data: SongBookExportDto;
}

