// @ts-nocheck
/**
 * Lyricast Dictionary API
 * API для работы со справочниками песен/Библии на основе SQLite
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LyricLine { 
    id: number;
    lyricId: number;
    rangeIndex?: string | null;
    lineIndex: number;
    globalSongIndex?: number | null;
    text: string;
}

