/**
 * Lyricast Dictionary API
 * API для работы со справочниками песен/Библии на основе SQLite
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RegistryItemMeta } from './registryItemMeta';


export interface RegistryItem { 
    db: string;
    size: number;
    mtime: number;
    meta?: RegistryItemMeta | null;
    /**
     * Сообщение об ошибке чтения метаданных для данной БД (если есть)
     */
    metaError?: string | null;
}

