// @ts-nocheck
/**
 * Dictionary API
 * API for dictionaries (songs, bibles, programs)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RegistryItemMetaDto } from './registryItemMetaDto';


export interface RegistryItemDto { 
    id: number;
    fileKey: string;
    humanName: string;
    catalogId: number;
    meta?: RegistryItemMetaDto;
}

