// @ts-nocheck
/**
 * Dictionary API
 * API for dictionaries (songs, bibles, programs)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SongBookExportLyricDto } from './songBookExportLyricDto';
import { SongBookExportBookNameDto } from './songBookExportBookNameDto';


export interface SongBookExportSongDto { 
    number: number;
    title: string;
    key: string;
    keySignature: string;
    author: string;
    meta: Array<string>;
    lyrics: Array<SongBookExportLyricDto>;
    ref: string | null;
    category: string | null;
    bookName: SongBookExportBookNameDto;
}

