// @ts-nocheck
/**
 * Lyricast Dictionary API
 * API для работы со справочниками песен/Библии на основе SQLite
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Lyric } from './lyric';


export interface SongSaveRequest { 
    id?: number | null;
    bookFileKey: string;
    number: number;
    title: string;
    songKey?: string;
    keySignature?: string;
    author?: string;
    ref?: string | null;
    category?: string | null;
    /**
     * Полная структура куплетов/припевов и строк, такая же как у SongFull.lyrics
     */
    lyrics?: Array<Lyric>;
}

