// @ts-nocheck
/**
 * Lyricast Dictionary API
 * API для работы со справочниками песен/Библии на основе SQLite
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SongBookExportSong } from './songBookExportSong';
import { SongBookExportHeader } from './songBookExportHeader';


/**
 * Полная структура экспортируемой книги песен (ISongBook)
 */
export interface SongBookExport { 
    header: SongBookExportHeader;
    /**
     * Метаданные книги (из song_book_meta)
     */
    meta: { [key: string]: string; };
    songs: Array<SongBookExportSong>;
}

