// @ts-nocheck
/**
 * Dictionary API
 * API for dictionaries (songs, bibles, programs)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SongLyricDto } from './songLyricDto';


export interface UpdateSongDto { 
    songBookId?: number;
    number?: number;
    title?: string;
    songKey?: string;
    keySignature?: string;
    author?: string;
    ref?: string;
    category?: string;
    meta?: Array<string>;
    lyrics?: Array<SongLyricDto>;
    id?: number;
    deleteMetaKeys?: Array<string>;
}

