/* 🤖 this file was generated by svg-to-ts */

import type { LyriIcon } from './lyri-icons/lyri-svg-icon.model';

export type LyriIconNameSubset<T extends Readonly<LyriIcon[]>> =
  T[number]['name'];

export * from './lyri-icons/lyri-bible.icon';
export * from './lyri-icons/lyri-bullet-list.icon';
export * from './lyri-icons/lyri-control.icon';
export * from './lyri-icons/lyri-grid.icon';
export * from './lyri-icons/lyri-opened-book.icon';
export * from './lyri-icons/lyri-play.icon';
export * from './lyri-icons/lyri-song-lyrics.icon';
export * from './lyri-icons/lyri-song.icon';
export * from './lyri-icons/lyri-stop.icon';
export * from './lyri-icons/lyri-storyboard.icon';
export * from './lyri-icons/lyri-svg-icon.model';
