/* 🤖 this file was generated by svg-to-ts */

export type LyriIconName =
  | 'bible'
  | 'control'
  | 'opened_book'
  | 'song_lyrics'
  | 'song'
  | 'storyboard';
export interface LyriIcon {
  name: LyriIconName;
  data: string;
}
