/* 🤖 this file was generated by svg-to-ts */
export const lyriPlay: {
  name: 'play';
  data: string;
} = {
  name: 'play',
  data: `<svg width="10" height="12" viewBox="0 0 10 12" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M0.666016 0.283203V11.9499L9.83268 6.11654L0.666016 0.283203Z" fill="currentColor"/></svg>`,
};
