/* 🤖 this file was generated by svg-to-ts */
export const lyriStop: {
  name: 'stop';
  data: string;
} = {
  name: 'stop',
  data: `<svg width="11" height="10" viewBox="0 0 11 10" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M10.5 10H0.5V0H10.5V10Z" fill="currentColor"/></svg>`,
};
