// @ts-nocheck
/**
 * Lyricast Dictionary API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AllBooksResponseBooksInner } from './allBooksResponseBooksInner';


export interface AllBooksResponse { 
    ok: boolean;
    books: Array<AllBooksResponseBooksInner>;
    totalCount: number;
}

