/**
 * Lyricast Dictionary API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ApiPhpActionSongSavePost200Response { 
    ok: boolean;
    db: string;
    id: number;
}

