// @ts-nocheck
/**
 * Lyricast Dictionary API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RegistryItem } from './registryItem';


export interface ApiPhpActionRegistryListGet200Response { 
    ok: boolean;
    /**
     * Имя каталога DATA_DIR
     */
    dir: string;
    items: Array<RegistryItem>;
    totalCount: number;
}

