/**
 * Lyricast Dictionary API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AuthResponse { 
    ok: boolean;
    token: string;
    userId: number;
    deviceId: number;
    /**
     * Время жизни токена в секундах
     */
    expiresIn: number;
}

