// @ts-nocheck
/**
 * Dictionary API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AuthControllerLogin200Response { 
    ok: boolean;
    token: string;
    userId: number;
    deviceId: number;
    expiresIn: number;
}

