// @ts-nocheck
/**
 * Lyricast Dictionary API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BookMetaSaveRequest { 
    /**
     * song_books.file_key, который нужно обновить
     */
    fileKey: string;
    /**
     * Объект ключ-значение, который будет upsert-нут в song_book_meta
     */
    meta?: { [key: string]: string; } | null;
    /**
     * Список meta-ключей, которые нужно удалить
     */
    deleteKeys?: Array<string> | null;
}

