// @ts-nocheck
/**
 * Lyricast Dictionary API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BookUpdateItem } from './bookUpdateItem';


export interface BookVersionsCheckResponse { 
    ok: boolean;
    db: string;
    updates: Array<BookUpdateItem>;
    totalCount: number;
}

