// @ts-nocheck
/**
 * Dictionary API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CatalogDto { 
    /**
     * ID каталога
     */
    id: number;
    /**
     * Уникальный код/slug
     */
    code: string;
    /**
     * Название каталога
     */
    title: string;
    /**
     * Тип каталога
     */
    type: CatalogDtoTypeEnum;
    /**
     * Текущая версия каталога
     */
    version: number;
    /**
     * Дата обновления
     */
    updatedAt: string;
    /**
     * Произвольные метаданные каталога
     */
    meta?: { [key: string]: string; };
}
export enum CatalogDtoTypeEnum {
    Songs = 'songs',
    Bible = 'bible',
    Program = 'program',
    Generic = 'generic'
};



