// @ts-nocheck
/**
 * Dictionary API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateCatalogDto { 
    /**
     * Уникальный код/slug. Если не передан — сгенерируется автоматически из title.
     */
    code?: string;
    /**
     * Человекочитаемое название каталога
     */
    title: string;
    /**
     * Тип каталога
     */
    type: CreateCatalogDtoTypeEnum;
}
export enum CreateCatalogDtoTypeEnum {
    Songs = 'songs',
    Bible = 'bible',
    Program = 'program',
    Generic = 'generic'
};



