// @ts-nocheck
/**
 * Dictionary API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateSongBookDto { 
    /**
     * ID каталога, в который создаётся сборник
     */
    catalogId: number;
    /**
     * Название сборника (meta.title)
     */
    title?: string;
    /**
     * Источник/автор (meta.source)
     */
    source?: string;
    /**
     * Язык сборника (meta.language)
     */
    language?: string;
    /**
     * Описание (meta.description)
     */
    description?: string;
    /**
     * Обложка в формате data URL
     */
    coverImage?: string;
    /**
     * Пользовательский fileKey (если не указан, генерится автоматически)
     */
    fileKey?: string;
}

