// @ts-nocheck
/**
 * Lyricast Dictionary API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LyricLine } from './lyricLine';


export interface Lyric { 
    id: number;
    songId: number;
    uniqId: string;
    sectionTitle: string;
    type: string;
    splitLinesCount?: number | null;
    sortIndex?: number | null;
    lines: Array<LyricLine>;
}

