// @ts-nocheck
/**
 * Dictionary API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RegistryItemMetaDto { 
    fileKey?: string;
    language?: string;
    title?: string;
    description?: string;
    coverImage?: string;
    version: number;
    updatedBy?: string;
    updatedAt?: string;
    songCount: number;
}

