// @ts-nocheck
/**
 * Dictionary API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RegistryItemDto } from './registryItemDto';


export interface RegistryResponseDto { 
    items: Array<RegistryItemDto>;
    totalCount: number;
}

