// @ts-nocheck
/**
 * Dictionary API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SongBookExportHeaderDto } from './songBookExportHeaderDto';
import { SongBookExportSongDto } from './songBookExportSongDto';


export interface SongBookExportDto { 
    header: SongBookExportHeaderDto;
    meta: { [key: string]: string; };
    songs: Array<SongBookExportSongDto>;
}

