// @ts-nocheck
/**
 * Lyricast Dictionary API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SongBookExportLyricLine } from './songBookExportLyricLine';


/**
 * Секция песни (куплет/припев) в экспортируемой книге
 */
export interface SongBookExportLyric { 
    songId: string;
    uniqId: string;
    sectionTitle: string;
    type: string;
    splitLinesCount: number;
    lines: Array<SongBookExportLyricLine>;
}

