// @ts-nocheck
/**
 * Dictionary API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SongBookExportLyricLineDto } from './songBookExportLyricLineDto';


export interface SongBookExportLyricDto { 
    songId: string;
    uniqId: string;
    sectionTitle: string;
    type: string;
    splitLinesCount: number;
    lines: Array<SongBookExportLyricLineDto>;
}

