// @ts-nocheck
/**
 * Lyricast Dictionary API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Строка текста в экспортируемой песне
 */
export interface SongBookExportLyricLine { 
    id: number;
    /**
     * Номер песни в виде строки
     */
    songId: string;
    rangeIndex?: string | null;
    index: number;
    globalSongIndex?: number | null;
    text: string;
}

