// @ts-nocheck
/**
 * Dictionary API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SongLyricLineDto } from './songLyricLineDto';


export interface SongLyricDto { 
    uniqId: string;
    sectionTitle: string;
    type: string;
    splitLinesCount: number;
    sortIndex: number;
    lyrics: Array<SongLyricLineDto>;
}

