// @ts-nocheck
/**
 * Dictionary API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SongLyricLineDto { 
    rangeIndex: string;
    lineIndex: number;
    globalSongIndex: number;
    text: string;
    repeatCount: number;
}

