// @ts-nocheck
/**
 * Lyricast Dictionary API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Lyric } from './lyric';


export interface SongFull { 
    id: number;
    bookFileKey: string;
    number: number;
    title: string;
    songKey: string;
    keySignature: string;
    author: string;
    ref?: string | null;
    category?: string | null;
    lyrics: Array<Lyric>;
}

