// @ts-nocheck
/**
 * Dictionary API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SongBookExportHeaderDto { 
    number: string;
    title: string;
    author: string;
    updatedAt: string;
    bookKey: string;
    disabled: boolean;
}

