// @ts-nocheck
/**
 * Dictionary API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SongBookExportLyricLineDto { 
    id: number;
    /**
     * Номер песни строкой
     */
    songId: string;
    rangeIndex: string | null;
    index: number;
    globalSongIndex: number | null;
    text: string;
}

