// @ts-nocheck
/**
 * Lyricast Dictionary API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SongSearchResponseItemsInner } from './songSearchResponseItemsInner';


export interface SongSearchResponse { 
    ok: boolean;
    db: string;
    page: number;
    pageSize: number;
    total: number;
    totalCount: number;
    /**
     * Если includeLyrics=0 — массив SongBase. Если includeLyrics=1 — массив SongFull. 
     */
    items: Array<SongSearchResponseItemsInner>;
}

