// @ts-nocheck
/**
 * Dictionary API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateCatalogDto { 
    /**
     * Уникальный код/slug. Если не передан — сгенерируется автоматически из title.
     */
    code?: string;
    /**
     * Человекочитаемое название каталога
     */
    title?: string;
    /**
     * Тип каталога
     */
    type?: UpdateCatalogDtoTypeEnum;
    meta?: { [key: string]: string; };
    deleteKeys?: Array<string>;
}
export enum UpdateCatalogDtoTypeEnum {
    Songs = 'songs',
    Bible = 'bible',
    Program = 'program',
    Generic = 'generic'
};



