// @ts-nocheck
/**
 * Dictionary API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BookVersionItemDto } from './bookVersionItemDto';


export interface VersionsCheckRequestDto { 
    books?: Array<BookVersionItemDto>;
}

