// @ts-nocheck
/**
 * Dictionary API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VersionsCheckResponseItemDto } from './versionsCheckResponseItemDto';


export interface VersionsCheckResponseDto { 
    updates: Array<VersionsCheckResponseItemDto>;
    totalCount: number;
}

